package payload

import (
	"bytes"
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	vmguest "github.com/Mavergreen/vm-guest"
	"github.com/Mavergreen/vm-guest/internal/config"
	"github.com/Mavergreen/vm-guest/internal/fetch"
	"github.com/Mavergreen/vm-guest/internal/proc"
)

// Identifier and Version are the package's own identity, exactly as
// build-firstboot-pkg.sh hardcodes them.
const (
	Identifier = "com.mqg.firstboot"
	Version    = "1.0"
)

// confHeader is the first line of every firstboot.conf, byte for byte.
// It stays the shell script's own path -- not this package's -- because
// docs/decisions/0011 fixes a `--updates none` conf as the P5 performance
// baseline: changing this line would change that file's bytes for no
// reason connected to what it says.
const confHeader = "# Generated by image/payload/build-firstboot-pkg.sh. Do not edit.\n"

// Config is a first-boot package's parameters: build-firstboot-pkg.sh's
// flags, one field each.
type Config struct {
	User      string
	RealName  string
	Hostname  string
	Shell     string
	UID       int
	GID       int
	AutoLogin bool
	Password  string

	SSHKey string

	// OpenSSHPkgs are paths to the guest's own OpenSSH product archives
	// (see image/fetch-openssh.sh); their basenames are what firstboot.conf
	// carries and firstboot.sh installs.
	OpenSSHPkgs []string
	OpenSSHTag  string

	// UpdatePkgs are paths to Apple's post-10.9.5 update packages, IN
	// INSTALL ORDER: see the ORDER MATTERS comment in
	// build-firstboot-pkg.sh's usage text.
	UpdatePkgs []string
	Updates    string
}

// DefaultConfig is build-firstboot-pkg.sh's defaults, MEASURED from that
// script: user mavsuser, uid 501, gid 20 (staff), realname "Mavericks
// User", hostname mavericks, shell /bin/bash, auto-login on, no password,
// no OpenSSH, updates none.
func DefaultConfig() Config {
	return Config{
		User:      "mavsuser",
		RealName:  "Mavericks User",
		Hostname:  "mavericks",
		Shell:     "/bin/bash",
		UID:       501,
		GID:       20,
		AutoLogin: true,
		Updates:   "none",
	}
}

func boolDigit(b bool) string {
	if b {
		return "1"
	}
	return "0"
}

// spaceBasenames is `for p in $paths; do printf '%s ' "$(basename "$p")"; done`:
// each basename followed by one space, in the order given.
func spaceBasenames(paths []string) string {
	var b strings.Builder
	for _, p := range paths {
		b.WriteString(filepath.Base(p))
		b.WriteByte(' ')
	}
	return b.String()
}

// quoteField is bashQuote with the field name attached to any error, so a
// value that cannot be quoted says which Config field it came from.
func quoteField(field, val string) (string, error) {
	q, err := bashQuote(val)
	if err != nil {
		return "", fieldErrorf(field, "%w", err)
	}
	return q, nil
}

// fieldErrorf is fmt.Errorf with a Config field name prefixed, for every
// error Build and its validation report: "every error names the field or
// path it concerns". The inner fmt.Errorf(format, a...) passes format and
// a straight through, in that order, which is the shape go vet's printf
// analyzer recognises as a wrapper -- so a call site's arguments are
// still checked against its own format string, the same as any direct
// fmt.Errorf call. (Confirmed by temporarily planting a mismatched call
// and re-running go vet; the plant was not committed.) The outer call's
// own format is the literal "%s: %w", not a field name, so this also
// never trips staticcheck's capitalized-error-string check (ST1005) the
// way a literal "Updates: ..." would.
func fieldErrorf(field, format string, a ...any) error {
	return fmt.Errorf("%s: %w", field, fmt.Errorf(format, a...))
}

// Conf renders firstboot.conf, byte for byte as build-firstboot-pkg.sh's
// printf block does: the header, the account fields, MQG_FB_ADMIN_GID
// (fixed at 80, never configurable -- see build-firstboot-pkg.sh), the
// OpenSSH block, the updates block (only when there are packages to
// name), and the password (only when set). Every value is bashQuote'd.
func Conf(c Config) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(confHeader)

	type kv struct{ field, key, val string }
	line := func(f kv) error {
		q, err := quoteField(f.field, f.val)
		if err != nil {
			return err
		}
		fmt.Fprintf(&b, "%s=%s\n", f.key, q)
		return nil
	}

	for _, f := range []kv{
		{"User", "MQG_FB_USER", c.User},
		{"UID", "MQG_FB_UID", strconv.Itoa(c.UID)},
		{"GID", "MQG_FB_GID", strconv.Itoa(c.GID)},
	} {
		if err := line(f); err != nil {
			return nil, err
		}
	}
	b.WriteString("MQG_FB_ADMIN_GID=80\n")

	for _, f := range []kv{
		{"RealName", "MQG_FB_REALNAME", c.RealName},
		{"Shell", "MQG_FB_SHELL", c.Shell},
		{"Hostname", "MQG_FB_HOSTNAME", c.Hostname},
		{"AutoLogin", "MQG_FB_AUTOLOGIN", boolDigit(c.AutoLogin)},
	} {
		if err := line(f); err != nil {
			return nil, err
		}
	}

	if len(c.OpenSSHPkgs) > 0 {
		b.WriteString("MQG_FB_OPENSSH=1\n")
		if err := line(kv{"OpenSSHTag", "MQG_FB_OPENSSH_TAG", c.OpenSSHTag}); err != nil {
			return nil, err
		}
		if err := line(kv{"OpenSSHPkgs", "MQG_FB_EXTRA_PKGS", spaceBasenames(c.OpenSSHPkgs)}); err != nil {
			return nil, err
		}
	} else {
		b.WriteString("MQG_FB_OPENSSH=0\n")
	}

	// Written only when there is something to say: a --updates none
	// image's conf is byte-identical to one built before a second value
	// existed (docs/decisions/0011). See TestANoneConfSaysNothingAboutUpdates.
	if len(c.UpdatePkgs) > 0 {
		if err := line(kv{"Updates", "MQG_FB_UPDATES", c.Updates}); err != nil {
			return nil, err
		}
		if err := line(kv{"UpdatePkgs", "MQG_FB_UPDATE_PKGS", spaceBasenames(c.UpdatePkgs)}); err != nil {
			return nil, err
		}
	}

	if c.Password != "" {
		if err := line(kv{"Password", "MQG_FB_PASSWORD", c.Password}); err != nil {
			return nil, err
		}
	}

	return b.Bytes(), nil
}

// embedMarker is the line build-firstboot-pkg.sh's assembly step
// substitutes in image/payload/postinstall.
const embedMarker = "#MQG_EMBEDDED_FILES\n"

// embedBlock writes one of embed()'s four blocks: say, a quoted heredoc,
// then a chmod, exactly as build-firstboot-pkg.sh's embed() function
// does -- with one deliberate difference. embed() ends the heredoc with
// `cat "$src"` followed by a bare `printf 'MQG_EOF_%s\n'`: if src's last
// line has no trailing newline, that printf's output lands on the SAME
// line as the content instead of terminating the heredoc, and `cat`
// silently glues them together. Here, a missing trailing newline gets one
// appended before the terminator, so the heredoc always closes. See
// TestAMissingTrailingNewlineStillTerminatesTheHeredoc.
func embedBlock(b *bytes.Buffer, v, dst, mode string, content []byte) {
	fmt.Fprintf(b, "say \"writing %s\"\n", dst)
	fmt.Fprintf(b, "cat > \"%s\" <<'MQG_EOF_%s'\n", dst, v)
	b.Write(content)
	if len(content) == 0 || content[len(content)-1] != '\n' {
		b.WriteByte('\n')
	}
	fmt.Fprintf(b, "MQG_EOF_%s\n", v)
	fmt.Fprintf(b, "chmod %s \"%s\" 2>/dev/null\n\n", mode, dst)
}

// Postinstall assembles the package's one Scripts member: the embedded
// image/payload/postinstall template with its #MQG_EMBEDDED_FILES line
// replaced by four heredocs -- firstboot.sh, conf, the authorized key and
// the LaunchDaemon plist -- exactly as build-firstboot-pkg.sh's embed()
// calls and Python substitution do. $CONF_DIR and $DAEMON are written
// literally: they are variables for the installed script to expand on the
// guest, not here.
func Postinstall(conf, key []byte) ([]byte, error) {
	template, err := fs.ReadFile(vmguest.Files, "image/payload/postinstall")
	if err != nil {
		return nil, err
	}
	firstbootSh, err := fs.ReadFile(vmguest.Files, "image/payload/firstboot.sh")
	if err != nil {
		return nil, err
	}
	plist, err := fs.ReadFile(vmguest.Files, "image/payload/com.mqg.firstboot.plist")
	if err != nil {
		return nil, err
	}

	var body bytes.Buffer
	embedBlock(&body, "FIRSTBOOT_SH", "$CONF_DIR/firstboot.sh", "755", firstbootSh)
	embedBlock(&body, "FIRSTBOOT_CONF", "$CONF_DIR/firstboot.conf", "600", conf)
	embedBlock(&body, "AUTHORIZED_KEYS", "$CONF_DIR/authorized_keys", "644", key)
	embedBlock(&body, "LAUNCHDAEMON", "$DAEMON", "644", plist)

	idx := bytes.Index(template, []byte(embedMarker))
	if idx < 0 {
		return nil, fmt.Errorf("image/payload/postinstall has no %s line to substitute", strings.TrimSuffix(embedMarker, "\n"))
	}
	out := make([]byte, 0, len(template)+body.Len())
	out = append(out, template[:idx]...)
	out = append(out, body.Bytes()...)
	out = append(out, template[idx+len(embedMarker):]...)
	return out, nil
}

var keyLineRE = regexp.MustCompile(`(?m)^(ssh|ecdsa)-`)

// keyLines is every non-empty, non-comment line of an authorized_keys
// file, trimmed: what carries a key. A line whose first non-whitespace
// character is '#' is a comment and is never a key -- not for the
// Ed25519 refusal below, not for the per-line "may not understand it"
// warning, and not for Build's "authorized key:" log line.
//
// This is a deliberate ruling, not a literal port: build-firstboot-pkg.sh
// runs `awk '{print $1}'` over EVERY line, comments included, and matches
// `case *ed25519*` against the whole multi-line result -- so a key file
// with a `# my laptop key` comment above an Ed25519 key IS refused by the
// shell (MEASURED: awk's $1 for that comment line is "#", but the
// Ed25519 line's "ssh-ed25519" is still present as a substring of the
// joined multi-line string, which `*ed25519*` matches), while the Go
// code here previously looked only at the first line and so missed it
// entirely -- a mistake that ALSO made Build's "authorized key:" log line
// print "#", not the key's real type. Scanning every non-comment line,
// rather than reproducing the shell's join-then-glob quirk, fixes both:
// see TestKeyRules for the failing case this replaces.
func keyLines(key []byte) []string {
	var out []string
	for _, line := range strings.Split(string(key), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	return out
}

func matchesAny(s string, choices ...string) bool {
	for _, c := range choices {
		if s == c {
			return true
		}
	}
	return false
}

// validateKey applies build-firstboot-pkg.sh's SSH key rules to an
// already-read key file, given by path only for error messages.
//
// One deliberate reordering from the shell script: there, the grep for a
// line starting ssh-/ecdsa- runs before the PRIVATE-key check, so a real
// OpenSSH private key (which has no such line) is refused with "does not
// look like an SSH public key" rather than the more specific PRIVATE
// message. Here the PRIVATE check runs first, so that specific mistake
// gets the specific, more useful answer. See TestKeyRules.
func validateKey(path string, key []byte, hasOpenSSH bool, tag string, log func(string, ...any)) error {
	head := key
	if len(head) > 64 {
		head = head[:64]
	}
	if bytes.Contains(head, []byte("PRIVATE")) {
		return fieldErrorf("SSHKey", "%s looks like a PRIVATE key; pass the .pub", path)
	}
	if !keyLineRE.Match(key) {
		return fieldErrorf("SSHKey", "%s does not look like an SSH public key", path)
	}

	lines := keyLines(key)

	// The Ed25519 refusal looks at EVERY non-comment line, not just the
	// first: see keyLines' comment for the MEASURED shell behavior this
	// fixes. Checked in its own pass, before any warning, so a later
	// line's refusal is never preceded by an earlier line's warning.
	if !hasOpenSSH {
		for _, line := range lines {
			typ := strings.Fields(line)[0]
			if strings.Contains(typ, "ed25519") {
				return fieldErrorf("SSHKey", "%s is an Ed25519 key, and a stock OS X 10.9 guest cannot use one: "+
					"it ships OpenSSH 6.2, and Ed25519 arrived in 6.5. Build the image with the family's OpenSSH "+
					"(the default -- see image/build-image.sh --openssh), or use an RSA or ECDSA key: "+
					"ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa", path)
			}
		}
	}

	for _, line := range lines {
		typ := strings.Fields(line)[0]
		var ok bool
		if hasOpenSSH {
			ok = matchesAny(typ, "ssh-ed25519", "ssh-rsa", "ssh-dss") ||
				strings.HasPrefix(typ, "ecdsa-sha2-") || strings.HasPrefix(typ, "sk-")
		} else {
			ok = matchesAny(typ, "ssh-rsa", "ssh-dss") || strings.HasPrefix(typ, "ecdsa-sha2-")
		}
		if ok || log == nil {
			continue
		}
		if hasOpenSSH {
			log("%s is a %s key; OpenSSH %s may not understand it", path, typ, tag)
		} else {
			log("%s is a %s key; OS X 10.9's OpenSSH 6.2 may not understand it", path, typ)
		}
	}
	return nil
}

// validatePkgs applies build-firstboot-pkg.sh's --openssh-pkg/--update-pkg
// rules to a Config field's list of package paths: each must exist, carry
// the xar magic, and have a basename with no whitespace (the names travel
// through a space-separated shell list in firstboot.conf).
func validatePkgs(field string, pkgs []string) error {
	for _, p := range pkgs {
		if _, err := os.Stat(p); err != nil {
			return fieldErrorf(field, "no such package: %s", p)
		}
		ok, err := fetch.HasXarMagic(p)
		if err != nil {
			return fieldErrorf(field, "%s: %w", p, err)
		}
		if !ok {
			return fieldErrorf(field, "%s is not a flat package (no xar magic)", p)
		}
		base := filepath.Base(p)
		if strings.ContainsAny(base, " \t\n\r\v\f") {
			return fieldErrorf(field, "name contains whitespace: %s", base)
		}
	}
	return nil
}

// validateConfig applies every build-firstboot-pkg.sh rule that can be
// checked before assembling anything, in the same order that script
// checks them (bar the key-validation reordering validateKey documents).
// It returns the key file's bytes, read once, so Build need not read it
// again.
func validateConfig(c Config, log func(string, ...any)) ([]byte, error) {
	if c.SSHKey == "" {
		return nil, fieldErrorf("SSHKey", "no SSH public key given")
	}
	key, err := os.ReadFile(c.SSHKey)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fieldErrorf("SSHKey", "no such SSH public key: %s", c.SSHKey)
		}
		return nil, fieldErrorf("SSHKey", "%w", err)
	}
	hasOpenSSH := len(c.OpenSSHPkgs) > 0
	if err := validateKey(c.SSHKey, key, hasOpenSSH, c.OpenSSHTag, log); err != nil {
		return nil, err
	}

	if err := validatePkgs("OpenSSHPkgs", c.OpenSSHPkgs); err != nil {
		return nil, err
	}
	if hasOpenSSH && c.OpenSSHTag == "" {
		return nil, fieldErrorf("OpenSSHTag", "required when OpenSSHPkgs is set -- "+
			"an image must record which OpenSSH it was built with")
	}

	if err := validatePkgs("UpdatePkgs", c.UpdatePkgs); err != nil {
		return nil, err
	}
	if !matchesAny(c.Updates, config.UpdateChoices...) {
		return nil, fieldErrorf("Updates", "unknown %q: choose one of %s", c.Updates, strings.Join(config.UpdateChoices, ", "))
	}
	if len(c.UpdatePkgs) > 0 && c.Updates == "none" {
		return nil, fieldErrorf("UpdatePkgs", "given but Updates is \"none\"; "+
			"the image would carry packages it does not admit to")
	}
	if len(c.UpdatePkgs) == 0 && c.Updates != "none" {
		return nil, fieldErrorf("Updates", "%q names no packages", c.Updates)
	}

	return key, nil
}

// Build validates c, assembles firstboot.conf and the postinstall script,
// checks the result is valid shell (via r, so a fake can refuse it in a
// test), packages it with flatPackage, and writes out and its out.sha256
// sidecar -- both by writing a temp file and renaming it into place, so a
// reader never sees a partial file. It returns the package's own sha256.
func Build(ctx context.Context, r proc.Runner, c Config, out string, log func(string, ...any)) (string, error) {
	if log == nil {
		log = func(string, ...any) {}
	}

	key, err := validateConfig(c, log)
	if err != nil {
		return "", err
	}

	conf, err := Conf(c)
	if err != nil {
		return "", err
	}
	post, err := Postinstall(conf, key)
	if err != nil {
		return "", err
	}

	tmp, err := os.CreateTemp("", "mqg-postinstall-*")
	if err != nil {
		return "", err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.Write(post); err != nil {
		tmp.Close()
		return "", err
	}
	if err := tmp.Close(); err != nil {
		return "", err
	}
	var stderr bytes.Buffer
	if err := r.Run(ctx, proc.Cmd{Name: "sh", Args: []string{"-n", tmpName}, Stderr: &stderr}); err != nil {
		if msg := strings.TrimSpace(stderr.String()); msg != "" {
			return "", fmt.Errorf("the assembled postinstall is not valid shell: %s: %w", msg, err)
		}
		return "", fmt.Errorf("the assembled postinstall is not valid shell: %w", err)
	}

	pkg, err := flatPackage(post, Identifier, Version)
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return "", err
	}
	if err := writeAtomic(out, pkg); err != nil {
		return "", err
	}

	sum, err := fetch.SHA256File(out)
	if err != nil {
		return "", err
	}
	sidecar := fmt.Sprintf("%s  %s\n", sum, filepath.Base(out))
	if err := writeAtomic(out+".sha256", []byte(sidecar)); err != nil {
		return "", err
	}

	log("built %s (%d bytes), sha256 %s", out, len(pkg), sum)
	for _, line := range keyLines(key) {
		fields := strings.Fields(line)
		typ, body := fields[0], ""
		if len(fields) > 1 {
			body = fields[1]
		}
		if len(body) > 16 {
			body = body[:16]
		}
		log("authorized key: %s %s...", typ, body)
	}

	return sum, nil
}

// writeAtomic writes data to path by creating path+".tmp", syncing it,
// and renaming it into place: a reader never sees a partial file. Build
// uses this for both the package itself and its out.sha256 sidecar.
func writeAtomic(path string, data []byte) error {
	tmp := path + ".tmp"
	f, err := os.Create(tmp)
	if err != nil {
		return err
	}
	if _, err := f.Write(data); err != nil {
		f.Close()
		os.Remove(tmp)
		return err
	}
	if err := f.Sync(); err != nil {
		f.Close()
		os.Remove(tmp)
		return err
	}
	if err := f.Close(); err != nil {
		os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return err
	}
	return nil
}
