// Package emit writes artifacts for other tools. Today: one Packer
// template, for the machine machine.ForInstall describes.
package emit

import (
	"fmt"

	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"

	"github.com/Mavergreen/vm-guest/internal/config"
	"github.com/Mavergreen/vm-guest/internal/machine"
)

type Variable struct{ Name, Description string }

// Variables are the user's own local paths. The template names them; it
// never carries what they hold.
var Variables = []Variable{
	{"media", "Installer media image from `vmavs media`"},
	{"ovmf_code", "OVMF_CODE.fd from `vmavs firmware`"},
	{"ovmf_vars", "This VM's own copy of OVMF_VARS.fd"},
	{"opencore_media", "OpenCore boot image from `vmavs firmware`"},
	{"ssh_key", "Private key whose public half the image's first-boot payload authorized"},
}

const header = `# Generated by vmavs emit packer. Do not edit; re-emit.
#
# WHAT IS AND IS NOT VERIFIED. The field names, nesting and types are
# MEASURED: packer validate (Packer 1.16.1, qemu plugin 1.1.6, vagrant
# plugin 1.1.7) accepts this template, and this project's CI re-validates
# it on every push. The values are the machine vmavs installs and boots.
# No Packer build has ever run from it, so whether the drive mapping and
# the SSH forward work in a real build is REASONED.
#
# NO APPLE BYTES. This template names local paths you produced; it
# contains none of Apple's software, and must never be changed so that it
# does. A box built from it contains Apple's operating system and can never
# be shared, so there is deliberately no Vagrant Cloud upload here.
#
# NO boot_command. Apple's own installer reads rc.cdrom.local,
# minstallconfig.xml and OSInstall.collection off the media, so the install
# runs unattended with nobody typing at a console.
#
# DRIVES ARE IN qemuargs. Supplying any -drive in qemuargs replaces all of
# Packer's default drives (packer-plugin-qemu; REASONED from its source),
# and OpenCore does not see a CD-ROM installer (MEASURED in P4), so the
# installer and target are attached here as the install stage attaches them.

`

// firstClass are the QEMU flags Packer's own fields replace.
var firstClass = map[string]bool{
	"-accel": true, "-machine": true, "-cpu": true, "-m": true, "-smp": true,
	"-display": true, "-monitor": true,
}

func Packer(hw config.Machine, diskGB int) ([]byte, error) {
	if err := hw.Validate(); err != nil {
		return nil, err
	}
	spec := machine.ForInstall(hw,
		machine.Firmware{OVMFCode: "${var.ovmf_code}", OpenCore: "${var.opencore_media}"},
		"${var.ovmf_vars}", "output-mavericks/mavericks.qcow2", "${var.media}", "")
	args := spec.Args()
	var pairs [][2]string
	for i := 0; i+1 < len(args); i += 2 {
		if !firstClass[args[i]] {
			pairs = append(pairs, [2]string{args[i], args[i+1]})
		}
	}

	f := hclwrite.NewEmptyFile()
	root := f.Body()
	plugins := root.AppendNewBlock("packer", nil).Body().AppendNewBlock("required_plugins", nil).Body()
	for _, p := range []string{"qemu", "vagrant"} {
		plugins.SetAttributeValue(p, cty.ObjectVal(map[string]cty.Value{
			"source":  cty.StringVal("github.com/hashicorp/" + p),
			"version": cty.StringVal("~> 1"),
		}))
	}
	for _, v := range Variables {
		root.AppendNewline()
		b := root.AppendNewBlock("variable", []string{v.Name}).Body()
		b.SetAttributeTraversal("type", hcl.Traversal{hcl.TraverseRoot{Name: "string"}})
		b.SetAttributeValue("description", cty.StringVal(v.Description))
	}
	root.AppendNewline()
	src := root.AppendNewBlock("source", []string{"qemu", "mavericks"}).Body()
	ref := func(name string) hcl.Traversal {
		return hcl.Traversal{hcl.TraverseRoot{Name: "var"}, hcl.TraverseAttr{Name: name}}
	}
	src.SetAttributeTraversal("iso_url", ref("media"))
	src.SetAttributeValue("iso_checksum", cty.StringVal("none"))
	src.SetAttributeValue("disk_image", cty.False)
	src.SetAttributeValue("disk_size", cty.StringVal(fmt.Sprintf("%dM", diskGB*1024)))
	src.SetAttributeValue("format", cty.StringVal("qcow2"))
	src.SetAttributeValue("output_directory", cty.StringVal("output-mavericks"))
	src.SetAttributeValue("vm_name", cty.StringVal("mavericks.qcow2"))
	src.SetAttributeValue("accelerator", cty.StringVal(hw.Accel))
	src.SetAttributeValue("machine_type", cty.StringVal(hw.Type+",vmport=off"))
	src.SetAttributeValue("cpu_model", cty.StringVal(hw.CPU))
	src.SetAttributeValue("memory", cty.NumberIntVal(int64(hw.MemoryMB)))
	src.SetAttributeValue("cpus", cty.NumberIntVal(int64(hw.SMP)))
	src.SetAttributeValue("headless", cty.True)
	src.SetAttributeValue("boot_wait", cty.StringVal("0s"))
	src.SetAttributeValue("communicator", cty.StringVal("ssh"))
	src.SetAttributeValue("ssh_username", cty.StringVal(config.DefaultSSHUser))
	src.SetAttributeTraversal("ssh_private_key_file", ref("ssh_key"))
	src.SetAttributeValue("ssh_timeout", cty.StringVal("60m"))
	src.SetAttributeValue("host_port_min", cty.NumberIntVal(int64(hw.SSHPort)))
	src.SetAttributeValue("host_port_max", cty.NumberIntVal(int64(hw.SSHPort)))
	src.SetAttributeRaw("qemuargs", pairsTokens(pairs))
	root.AppendNewline()
	build := root.AppendNewBlock("build", nil).Body()
	build.SetAttributeValue("sources", cty.ListVal([]cty.Value{cty.StringVal("source.qemu.mavericks")}))
	build.AppendNewBlock("post-processor", []string{"vagrant"}).Body().
		SetAttributeValue("output", cty.StringVal("mavericks-{{.Provider}}.box"))

	return append([]byte(header), hclwrite.Format(f.Bytes())...), nil
}
