# Generated by vmavs emit packer. Do not edit; re-emit.
#
# WHAT IS AND IS NOT VERIFIED. The field names, nesting and types are
# MEASURED: packer validate (Packer 1.16.1, qemu plugin 1.1.6, vagrant
# plugin 1.1.7) accepts this template, and this project's CI re-validates
# it on every push. The values are the machine vmavs installs and boots.
# No Packer build has ever run from it, so whether the drive mapping and
# the SSH forward work in a real build is REASONED.
#
# NO APPLE BYTES. This template names local paths you produced; it
# contains none of Apple's software, and must never be changed so that it
# does. A box built from it contains Apple's operating system and can never
# be shared, so there is deliberately no Vagrant Cloud upload here.
#
# NO boot_command. Apple's own installer reads rc.cdrom.local,
# minstallconfig.xml and OSInstall.collection off the media, so the install
# runs unattended with nobody typing at a console.
#
# DRIVES ARE IN qemuargs. Supplying any -drive in qemuargs replaces all of
# Packer's default drives (packer-plugin-qemu; REASONED from its source),
# and OpenCore does not see a CD-ROM installer (MEASURED in P4), so the
# installer and target are attached here as the install stage attaches them.

packer {
  required_plugins {
    qemu = {
      source  = "github.com/hashicorp/qemu"
      version = "~> 1"
    }
    vagrant = {
      source  = "github.com/hashicorp/vagrant"
      version = "~> 1"
    }
  }
}

variable "media" {
  type        = string
  description = "Installer media image from `vmavs media`"
}

variable "ovmf_code" {
  type        = string
  description = "OVMF_CODE.fd from `vmavs firmware`"
}

variable "ovmf_vars" {
  type        = string
  description = "This VM's own copy of OVMF_VARS.fd"
}

variable "opencore_media" {
  type        = string
  description = "OpenCore boot image from `vmavs firmware`"
}

variable "ssh_key" {
  type        = string
  description = "Private key whose public half the image's first-boot payload authorized"
}

source "qemu" "mavericks" {
  iso_url              = var.media
  iso_checksum         = "none"
  disk_image           = false
  disk_size            = "61440M"
  format               = "qcow2"
  output_directory     = "output-mavericks"
  vm_name              = "mavericks.qcow2"
  accelerator          = "kvm"
  machine_type         = "q35,vmport=off"
  cpu_model            = "Penryn,+ssse3,+sse4.1,+sse4.2"
  memory               = 4096
  cpus                 = 2
  headless             = true
  boot_wait            = "0s"
  communicator         = "ssh"
  ssh_username         = "mavsuser"
  ssh_private_key_file = var.ssh_key
  ssh_timeout          = "60m"
  host_port_min        = 2222
  host_port_max        = 2222
  qemuargs = [
    ["-drive", "if=pflash,format=raw,unit=0,readonly=on,file=${var.ovmf_code}"],
    ["-drive", "if=pflash,format=raw,unit=1,file=${var.ovmf_vars}"],
    ["-device", "ich9-usb-ehci1,id=usb,bus=pcie.0,addr=0x1d.7,multifunction=on"],
    ["-device", "ich9-usb-uhci1,masterbus=usb.0,firstport=0,bus=pcie.0,addr=0x1d.0,multifunction=on"],
    ["-device", "ich9-usb-uhci2,masterbus=usb.0,firstport=2,bus=pcie.0,addr=0x1d.1"],
    ["-device", "ich9-usb-uhci3,masterbus=usb.0,firstport=4,bus=pcie.0,addr=0x1d.2"],
    ["-drive", "id=opencore,if=none,format=raw,snapshot=on,file=${var.opencore_media}"],
    ["-device", "usb-storage,bus=usb.0,drive=opencore"],
    ["-drive", "id=target,if=none,format=qcow2,file=output-mavericks/mavericks.qcow2"],
    ["-device", "ide-hd,bus=ide.0,drive=target"],
    ["-netdev", "user,id=net0,hostfwd=tcp:127.0.0.1:2222-:22"],
    ["-device", "e1000-82545em,netdev=net0"],
    ["-device", "usb-kbd,bus=usb.0"],
    ["-device", "usb-mouse,bus=usb.0"],
    ["-device", "VGA,vgamem_mb=64"],
    ["-drive", "id=installer,if=none,format=raw,snapshot=on,file=${var.media}"],
    ["-device", "ide-hd,bus=ide.1,drive=installer"],
  ]
}

build {
  sources = ["source.qemu.mavericks"]
  post-processor "vagrant" {
    output = "mavericks-{{.Provider}}.box"
  }
}
